export const TIMEZONES = [
  { label: 'Hawaii (HST)', offset: -10 },
  { label: 'Alaska (AKST)', offset: -9 },
  { label: 'California (PT)', offset: -8 },
  { label: 'Denver (MT)', offset: -7 },
  { label: 'Dallas (CT)', offset: -6 },
  { label: 'Florida (ET)', offset: -5 },
  { label: 'Puerto Rico (AT)', offset: -4 },
  { label: 'Brazil (BRT)', offset: -3 },
  { label: 'UK (GMT)', offset: 0 },
  { label: 'France (CET)', offset: 1 },
  { label: 'South Africa (SAST)', offset: 2 },
  { label: 'Moscow (MSK)', offset: 3 },
  { label: 'Dubai (GST)', offset: 4 },
  { label: 'Pakistan (PKT)', offset: 5 },
  { label: 'Bangladesh (BST)', offset: 6 },
  { label: 'Cambodia (ICT)', offset: 7 },
  { label: 'Singapore (SGT)', offset: 8 },
  { label: 'Japan (JST)', offset: 9 },
  { label: 'Sydney (AEST)', offset: 10 },
  { label: 'New Zealand (NZST)', offset: 12 },
];
